/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seconds;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import org.apache.commons.io.IOUtils;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Sapumal Bandara
 */
public class time extends javax.swing.JFrame {

    /**
     * Creates new form time
     */
    public time() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
 
    }

    Timer timer;
    int second, minute;
    String strSecond, strMinute;
    DecimalFormat df = new DecimalFormat("00");

    public void cdtimer() {

        timer = new Timer(1000, (ActionEvent e) -> {

            second--;

            if (second == -1) {
                second = 59;
                minute--;
            }

            if (second == 0 && minute == 0) {

                timer.stop();
            }

            strSecond = df.format(second);
            strMinute = df.format(minute);

            jLabel1.setText(strMinute + ":" + strSecond);

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 106, 54));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("00:00");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 186, 240, 110));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 330, 40));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 42, 330, 40));

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 106, 54));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 433, 380, 193));

        jButton3.setText("up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 46));

        jButton4.setText("dn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        second = 0;
        minute = 1;
        cdtimer();
        timer.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            get_quote();        // TODO add your handling code here:
        } catch (JSONException ex) {
            Logger.getLogger(time.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
      //  String split[] =jLabel1.getText();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void get_quote() throws JSONException {
 
        try {

//                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                    String DueDate = sdf.format(dc_duedate.getDate());
//
//                    String user_id = "103444";
//                    String sender_id = "WDComputers";
//                    String api_key = "yqdqt02fznsea0fvp";
//                    String to = MobileNo;
//                    String ORI_message = "Welcome. Your New Job No. is : " + LastTickeNo + " And Due Date: " + DueDate + "";
//
//                    String message = ORI_message.replaceAll("\\n+", "%20").replaceAll("&", "and").replaceAll("'", "").replaceAll("\\s+", "%20");
            String zen_quotes = "https://zenquotes.io/api/random";
            String inspirational_quotes="https://lucifer-quotes.vercel.app/api/quotes";
            URL url = new URL("https://zenquotes.io/api/random");
            // URL url = new URL("http://send.ozonedesk.com/api/v2/send.php?user_id=103423&api_key=5bngogeavejf70m6p&sender_id=ozoneDEMO&to=+94710721845&message=HAPPYBIRTHDAY ");

            System.out.println(url);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();

            connection.setRequestMethod("GET");
            connection.setConnectTimeout(5000);
            connection.setReadTimeout(5000);
            String s = connection.getResponseMessage();

            System.out.println("s: " + s);

            try ( // read the response
                    InputStream in = new BufferedInputStream(connection.getInputStream())) {
                String result = IOUtils.toString(in, "UTF-8");
                System.out.println(result);
//                
//                JSONObject obj = new JSONObject(result);
//                 
//                jTextArea1.setText("");
//                jTextArea1.setText(obj.getString("q"));

//                JSONArray json_arr = new JSONArray(result);
//                Object single_response = json_arr.get(0); //for single element
//                System.out.println(single_response);

                int i = result.indexOf("{");
                result = result.substring(i);
                JSONObject json = new JSONObject(result.trim());
                 
                
                jLabel2.setText("<html><p style =\"text-align:center\">"+json.getString("q")+"<br>"+"--"+json.getString("a")+"--" +"  </p> </html>");
                 

//            System.out.println("result after Reading JSON Response");
//                        JSONObject myResponse = new JSONObject(result);
//                        System.out.println("jsonrpc- " + myResponse.getString("jsonrpc"));
//                        System.out.println("id- " + myResponse.getInt("id"));
//                        System.out.println("result- " + myResponse.getString("result"));
            }

//                cmb_ticket_status_main.setSelectedItem(cmb_ticket_status.getSelectedItem().toString());
//
//                get_com_history();
//
//                txt_com_note.setText("");
        } catch (MalformedURLException e) {
        } catch (IOException ex) {
            Logger.getLogger(time.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
//                    con.close();
//                    pst.close();

        }

    }

}
